import { jsPDF } from "jspdf";

// shot is a dataURL (image/png), meta: { timestamp, emotion, innovationType }
export function buildVisitorPdf(shot, meta) {
  const doc = new jsPDF({ unit: "px", format: [800, 1131] }); // ~A4 portrait
  doc.setFillColor(0,0,0);
  doc.rect(0,0,800,1131,"F");

  // title
  doc.setTextColor(0,255,136);
  doc.setFontSize(28);
  doc.text("Innovation Visitor Snapshot", 40, 60);

  // selfie
  if (shot) {
    try {
      doc.addImage(shot, "PNG", 40, 90, 320, 240);
    } catch {}
  }

  doc.setTextColor(255,255,255);
  doc.setFontSize(16);
  const y0 = 360;
  doc.text(`Time: ${meta.timestamp}`, 40, y0);
  doc.text(`Dominant Emotion: ${meta.emotion}`, 40, y0+26);
  doc.text("Innovation Theme:", 40, y0+52);

  doc.setTextColor(180,220,255);
  doc.setFontSize(18);
  wrapText(doc, meta.innovationType || "", 40, y0+78, 720, 20);

  // footer
  doc.setTextColor(160,160,160);
  doc.setFontSize(12);
  doc.text("Generated by AI Booth – Monsha’at Innovation Center", 40, 1085);

  return doc;
}

function wrapText(doc, text, x, y, maxWidth, lineHeight) {
  const words = text.split(" ");
  let line = "";
  for (let n = 0; n < words.length; n++) {
    const testLine = line + words[n] + " ";
    const w = doc.getTextWidth(testLine);
    if (w > maxWidth && n > 0) {
      doc.text(line, x, y);
      line = words[n] + " ";
      y += lineHeight;
    } else {
      line = testLine;
    }
  }
  doc.text(line, x, y);
}
