import { jsPDF } from "jspdf";

// shot is a dataURL (image/png), meta: { timestamp, emotion, innovationType }
export function buildVisitorPdf(shot, meta) {
  const doc = new jsPDF({ unit: "px", format: [800, 1131] }); // ~A4 portrait

  // Background
  doc.setFillColor(0, 0, 0);
  doc.rect(0, 0, 800, 1131, "F");

  // English title
  doc.setTextColor(0, 255, 136);
  doc.setFontSize(28);
  doc.text("Innovation Visitor Snapshot", 40, 60);

  // Selfie (left)
  if (shot) {
    try {
      doc.addImage(shot, "PNG", 40, 90, 320, 240);
    } catch {}
  }

  // ------- Info block -------
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  const y0 = 360;

  const now = new Date();
  const visitTime =
    meta.timestamp ||
    now.toLocaleString("en-SA", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    });

  doc.text(`Visit Time: ${visitTime}`, 40, y0);
  doc.text(`Dominant Emotion: ${meta.emotion}`, 40, y0 + 26);
  doc.text("Innovation Theme:", 40, y0 + 52);

  doc.setTextColor(180, 220, 255);
  doc.setFontSize(18);
  wrapText(doc, meta.innovationType || "", 40, y0 + 78, 720, 20);

  // ------- English info block (Center Info) -------
  const xLeft = 40;
  let y = 520;

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("About Your Visit & The Innovation Center", xLeft, y);
  y += 30;

  doc.setFontSize(16);
  doc.setTextColor(200, 255, 200);
  doc.text(
    `You visited the Innovation Center booth at ${visitTime}, and we were honored by your presence! 🌟`,
    xLeft,
    y,
    { maxWidth: 720 }
  );
  y += 45;

  doc.setTextColor(255, 255, 255);
  const intro =
    "Here’s some information about the Innovation Center:\n" +
    "The center supports small and medium-sized enterprises (SMEs) " +
    "in developing their projects and provides incubation support programs.";
  wrapText(doc, intro, xLeft, y, 720, 22);
  y += 65;

  // Requirements
  doc.setTextColor(180, 220, 255);
  doc.setFontSize(18);
  doc.text("Requirements to Apply for Incubation:", xLeft, y);
  y += 28;

  doc.setTextColor(230, 230, 230);
  doc.setFontSize(16);
  const bullets = [
    "• Obtain a commercial registration from the Saudi Business Center",
    "• Have at least one team member",
    "• Have a business model",
    "• Have a prototype of your product or service",
  ];
  bullets.forEach((line) => {
    doc.text(line, xLeft, y, { maxWidth: 720 });
    y += 24;
  });

  // Contact info
  y += 20;
  doc.setTextColor(200, 255, 200);
  doc.text("Send your idea and requirements to:", xLeft, y);
  y += 24;

  doc.setTextColor(255, 255, 0);
  doc.text("innovationcenters@monshaat.gov.sa", xLeft, y);
  y += 30;

  doc.setTextColor(200, 255, 200);
  doc.text("Official Website:", xLeft, y);
  y += 22;

  doc.setTextColor(255, 255, 0);
  doc.text("https://innovationcenter.monshaat.gov.sa/", xLeft, y);

  // ------- footer -------
  doc.setTextColor(160, 160, 160);
  doc.setFontSize(12);
  doc.text("Generated by AI Booth – Monsha’at Innovation Center", 40, 1085);

  return doc;
}

// Simple LTR text wrapper (same as before)
function wrapText(doc, text, x, y, maxWidth, lineHeight) {
  const words = (text || "").split(" ");
  let line = "";
  for (let n = 0; n < words.length; n++) {
    const testLine = line + words[n] + " ";
    const w = doc.getTextWidth(testLine);
    if (w > maxWidth && n > 0) {
      doc.text(line, x, y);
      line = words[n] + " ";
      y += lineHeight;
    } else {
      line = testLine;
    }
  }
  if (line) doc.text(line, x, y);
}
